services:
  - type: web
    name: zova-shop
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
